spring.application.name=inventory-system
server.port=5050

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/inventory-system}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB

secreteJwtString=${SECRET_KEY:8f3a9c1d7e5b4a2f9d6c3e1b8a7f4c2d9e6b1a3f}