### GET request to get all patients
#GET http://lb-7e648e08.elb.localhost.localstack.cloud:4004/api/patients
#Authorization: Bearer {{token}}

#GET localhost:4004/patients/
GET localhost:4004/api/patients/9
Content-Type: application/json
###